# Zola build workflow.

# Prerequisites:
# - zola writes output to public/
# - variables below set correctly
#
# Setting it up:
#   It is a general limitation of gh-actions that they cannot make the very first
#   deploy to gh-pages.  It will seem to work, but not appear on the CDN to be
#   online.  You need to go to settings and set the gh-pages branch, then future
#   deploys will work.  See
#   https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token

name: Build/deploy website

env:
  ZOLA_VERSION: "0.16.1"
  MAIN_BRANCH: "main"
  TARGET_BRANCH: "gh-pages"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install zola
      run: |
        set -x
        wget -O - \
           "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin
    - name: Generate HTML
      run: zola build
    - name: Deploy to gh-pages
      if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.MAIN_BRANCH) }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
